CREATE TABLE PRODUCTO 
(
	ProductoID INT IDENTITY PRIMARY KEY,
	Descripcion VARCHAR(MAX)
)

CREATE TABLE LISTA 
(
	ListaID INT IDENTITY PRIMARY KEY,
	FechaCreacion DATETIME NOT NULL,
	FechaTerminacion DATETIME NULL,
	Supermercado VARCHAR(25) NULL
)

CREATE TABLE LISTA_DETALLE
(
	IDLista INT NOT NULL,
	IDProducto INT NOT NULL,
	CONSTRAINT PK_ListaDetalle PRIMARY KEY (IDLista,IDProducto),
	FOREIGN KEY (IDLista) REFERENCES LISTA(ListaID),
	FOREIGN KEY (IDProducto) REFERENCES PRODUCTO(ProductoID)
)